services:
  rocky10build:
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL10
        buildrepo: php81build
  rocky9build:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9
        buildrepo: php81build

volumes:
  rpm9rocky:
    name: rpm9rocky
  rpm10rocky:
    name: rpm10rocky
