services:
  rocky8build:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8
        buildrepo: php56build

volumes:
  rpm8rocky:
    name: rpm8rocky
