version: "3"
services:
  centos7pearbuildphp80:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.php8x
      args:
        centos: $OS7
        buildrepo: php80build
  stream8pearbuildphp80:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.php8x
      args:
        centos: $OS8
        buildrepo: php80build

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream
