version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.8

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  pearbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7pearbuildphp81rpm
          build_file: docker-compose.php81.yml
          build_service: centos7pearbuildphp81
          bintray_uploader: centos7bintray
          bintray-repo: php81custom
      - docker-rpmbuild/build:
          name: stream8pearbuildphp81rpm
          build_file: docker-compose.php81.yml
          build_service: stream8pearbuildphp81
          bintray_uploader: stream8bintray
          bintray-repo: php81custom
      - docker-rpmbuild/build:
          name: centos7pearbuildphp74rpm
          build_service: centos7pearbuildphp74
          bintray_uploader: centos7bintray
          bintray-repo: php74custom
      - docker-rpmbuild/build:
          name: stream8pearbuildphp74rpm
          build_service: stream8pearbuildphp74
          bintray_uploader: stream8bintray
          bintray-repo: php74custom
      - docker-rpmbuild/image:
          name: centos7pearbuildphp81
          compose_file: build/php81/docker-compose.yml
          build_service: centos7pearbuildphp81
          requires:
            - centos7pearbuildphp81rpm
      - docker-rpmbuild/image:
          name: stream8pearbuildphp81
          compose_file: build/php81/docker-compose.yml
          build_service: stream8pearbuildphp81
          requires:
            - stream8pearbuildphp81rpm
      - docker-rpmbuild/image:
          name: centos7pearbuildphp74
          compose_file: build/php74/docker-compose.yml
          build_service: centos7pearbuildphp74
          requires:
            - centos7pearbuildphp74rpm
      - docker-rpmbuild/image:
          name: stream8pearbuildphp74
          compose_file: build/php74/docker-compose.yml
          build_service: stream8pearbuildphp74
          requires:
            - stream8pearbuildphp74rpm